import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFile, mkdir } from 'node:fs/promises';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin:
https://github.com/wilfriedago/obsidian-tinymist
*/
`;

const prod = process.argv[2] === 'production';
const outDir = 'dist';

/**
 * `dist/` is the complete plugin folder, not just the bundle: Obsidian loads a
 * plugin from a directory containing `main.js`, `manifest.json` and
 * `styles.css` side by side. Copying the two static files in alongside the
 * bundle means `dist/` can be symlinked straight into a vault's plugins folder,
 * and the release workflow has one directory to upload from.
 */
const copyStaticAssets = {
	name: 'copy-static-assets',
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0) {
				return;
			}
			await mkdir(outDir, { recursive: true });
			await Promise.all([
				copyFile('manifest.json', `${outDir}/manifest.json`),
				copyFile('styles.css', `${outDir}/styles.css`),
			]);
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	// Obsidian supplies these at runtime. Bundling our own copy of the
	// CodeMirror packages would create a second, incompatible CM6 instance.
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	platform: 'node',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: `${outDir}/main.js`,
	minify: prod,
	plugins: [copyStaticAssets],
	define: {
		'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
	},
});

if (prod) {
	await context.rebuild();
	await context.dispose();
	process.exit(0);
} else {
	await context.watch();
}
